# Acme Insurance Rates

BASE_TERM_RATE = 59.94

ACTIVE_VOLCANO_STATES = {'AK', 'AZ', 'CA', 'CO', 'HI', 'ID', 'NV', 'NM', 'OR', 'UT', 'WA', 'WY'}

# FEES
HAS_CANCELLED_FEE = 0.15
NEAR_VOLCANO_FEE = 0.25

# DISCOUNTS
NOT_CANCELLED_DISCOUNT = -0.10
OWNERSHIP_DISCOUNT = -0.20
