# Generated by Django 4.0.6 on 2022-07-21 05:37

import acme_insurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(default=acme_insurance.models.get_random_id, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('effective_date', models.DateField()),
                ('has_cancelled', models.BooleanField()),
                ('owns_property', models.BooleanField()),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('base_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volcano_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('not_cancelled_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ownership_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
